# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71c761e361dcdb90d250fd2dc5d83e8fcce5f79d5e4097b1ca8639e92658531a0ef1259ec53ddaf509dfebd410e30e0f16c5124b1c4dc41c106cf2c7cc4eaa26

test:
  secret_key_base: 4ed5de7f0beabbd26f6f9d67e0780cd7eb503ab3a013506964ade3989d3f29d66cfc5158a52257454238bae793a8923d757f93d9800e6bf4050b2db7b58b8c12

demo:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
